#!/bin/bash

# This docker is contains an HDFS file system, accessed through hdfs server interface

if [ -z ${XFRAMES_HOME+x} ]
then
  echo "XFRAMES_HOME is not set"
  exit 1
fi

# Runs hdfs docker on localhost:8020/50070
# Make sure the hostname xpatterns-hadoop is mapped to 127.0.01 in /etc/hosts.
# 127.0.0.1 xpatterns-hadoop

CACHE=/tmp/hdfs-cache
sudo rm -rf $CACHE
mkdir $CACHE

docker run -dt -p 8020:8020 -p 50070:50070 -p 50075:50075 \
    -v "$CACHE":/var/lib/hadoop-hdfs/cache \
    -v "${XFRAMES_HOME}/dockdir":/opt/xframes \
    --name xframes-hdfs \
    --hostname xpatterns-hadoop xpatterns/hadoop:1.3.3 \
    /usr/bin/run.sh init
