#!/usr/bin/env bash

# Prepares files for docker build

cp -r ../intro notebooks

# Prepare build area
BUILD_DIR=/tmp/docker-build
rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
mkdir ${BUILD_DIR}/my
cp -r ../docs ${BUILD_DIR}
cp -r ../xframes ${BUILD_DIR}
cp -r ../xframes/conf ${BUILD_DIR}
cp Dockerfile ${BUILD_DIR}
cp server.sh ${BUILD_DIR}
