version: "3"

services:
  xframes:
    container_name: xframes
    build: .
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - 8888:8888
      - 4040-4048:4040-4048
    volumes:
      - ./notebooks:/home/jovyan/work
