#!/bin/bash

# This runs within the docker.
# It is used to copy data files into hdfs for use by the test suite.

hdfs dfs -mkdir /user/xframes
hdfs dfs -mkdir /user/xframes/files


hdfs dfs -copyFromLocal -f /opt/xframes/data/files/* /user/xframes/files/
